import type { Metadata } from "next";
import "../globals.css";
import Nav from "../ui/Nav";
import { getDictionary } from "./dictionaries";
import { getSession } from "../lib/session";
import Footer from "../ui/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangParams {
  lang: "en" | "ar";
}

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ar" }];
}
export const dynamicParams = false;
export default async function RootLayout({
  children,
  params,
  modal,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<LangParams>;
  modal: React.ReactNode;
}>) {
  const result = await getSession();
  const { lang } = await params;
  const t = await getDictionary(lang);
  return (
    <html
      lang={lang}
      dir={lang === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning={true}
    >
      <body
        className={`overflow-x-hidden min-h-screen  w-full flex flex-col justify-center relative items-center `}
      >
        <Nav
          t={t}
          user={result.success && result.user ? result.user : null}
        ></Nav>
        {modal}
        {children}
        <Footer lang={lang}></Footer>
      </body>
    </html>
  );
}
