import type { Metadata } from "next";
import "../globals.css";
import Nav from "../ui/Nav";
import { getDictionary } from "./dictionaries";
import { getSession } from "../lib/session";
import Footer from "../ui/Footer";
import { ToastContainer } from "react-toastify";
import { Home } from "lucide-react";
export const metadata: Metadata = {
  title: "Villadi co",
  description: "Generated by create next app",
};
import localFont from "next/font/local";
import Link from "next/link";
import { Head } from "next/document";

const myFont = localFont({
  src: "./fonts/taile.ttf",
});
const myFont2 = localFont({
  src: "./fonts/BritishCouncil-Arabic-Regular.ttf",
});

interface LangParams {
  lang: "en" | "ar";
}

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ar" }];
}
export const dynamicParams = false;
export default async function RootLayout({
  children,
  params,
  modal,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<LangParams>;
  modal: React.ReactNode;
}>) {
  const result = await getSession();
  const { lang } = await params;
  const t = await getDictionary(lang);

  return (
    <html
      lang={lang}
      dir={lang === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning={true}
      className={lang === "en" ? myFont.className : myFont2.className}
    >
      <link rel="icon" href="/villadiLogo.svg" />
      <body
        className={`overflow-x-hidden min-h-screen  w-full flex flex-col justify-center relative items-center `}
      >
        <ToastContainer />
        <Nav
          t={t}
          user={result.success && result.user ? result.user : null}
        ></Nav>
        {modal}
        {children}
        <Link
          href={`/${lang}`}
          className="fixed flex justify-center items-center w-[40px] bottom-[50px] right-[40px] z-[4] h-[40px] bg-black text-white rounded-2xl text-sm sm:text-lg shadow-[0px_0px_20px_9px]"
        >
          <Home />
        </Link>
        <Footer lang={lang}></Footer>
      </body>
    </html>
  );
}
